- name: Validate and reload SSH
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  notify: Reload SSH
- name: Reload SSH
  ansible.builtin.service:
    name: ssh
    state: reloaded
