main_domain: nmfdev.web.id
proxy_domain: ai-proxy.nmfdev.web.id
admin_user: nmfdev
ssh_port: 22
admin_authorized_key: "{{ vault_admin_authorized_key }}"
admin_password_hash: "{{ vault_admin_password_hash }}"
static_site_root: /var/www/nmfdev.web.id/html
omniroute_user: omniroute
omniroute_group: omniroute
omniroute_data_dir: /var/lib/omniroute
omniroute_config_dir: /etc/omniroute
omniroute_port: 20128
omniroute_package: omniroute@3.8.49
nodejs_major_version: 24
bun_version: "1.4.0"
bun_install_dir: /usr/local/bin
omniroute_memory_mb: 512
ssh_bootstrap_user: ubuntu
admin_shell: /bin/bash
enable_oh_my_zsh: true
oh_my_zsh_repo: https://github.com/ohmyzsh/ohmyzsh.git
oh_my_zsh_repo_revision: 146461f7c6d95f4ba1220559d66eb113418b40a8
